/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function copyRgbaWithRows(rgba: Uint8Array, width: number, height: number, bytesPerRow: number, dstBytesPerRow: number): Buffer

export declare function mergeAudioArrays(pcmArrays: Array<Buffer>, volumes: Array<number>): Buffer

export declare function rgbaToYuv420P(rgba: Uint8Array, width: number, height: number): Buffer

export declare function yuv420PToRgba(yuv: Uint8Array, width: number, height: number): Buffer
